### ISSUE TITLE
Shaping in health_gathering sometimes crashes

### ISSUE THREAD

**Issue by schrum2** [Marqt/ViZDoom#74] opened 2016-06-01 21:07 UTC
This error is annoying because it only happens periodically. I'm using the Shaping.java file in conjunction with the downloaded version 1.0.3 binary for Windows. I only noticed this error after doing this, but because it happens periodically, it may have been an issue before. The CFG and WAD are for the health_gathering task. I receive:

Exception in thread "main" vizdoom.ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.
    at vizdoom.DoomGame.makeAction(Native Method)
    at vizdoom.examples.Shaping.main(Shaping.java:72)

The specific line causing the problems is
double r = game.makeAction(actions.get(ran.nextInt(3)));
Even if I change the code to the following,
double r = game.makeAction(actions.get(0));
I sometimes get the error. The code crashes roughly 1 in 5 times, but there is a lot of variation.

Interestingly, when the code crashes, it is ALWAYS on the first action. The error is not occurring at some point in the middle of evaluation, but always at the very start of the very first episode.

**Comment by Marqt** [comment] 2016-06-01 22:08
I confirm that it happens on windows on 1.0.2 and 1.0.3. 1.0.1 works well so You can use this version for now. I will investigate this.

**Comment by Marqt** [comment] 2016-06-14 23:04
Sorry, I forgot a bit about this issue, however I think it has just been solved in new 1.1.0pre and 1.0.4 build.

**Comment by Marqt** [comment] 2016-12-06 10:00
I've checked again and I cannot reproduce this bug anymore (tested on Linux and Windows), so I'm closing this issue.

**Closed by Marqt** 2016-12-06 10:00 UTC
Labels: bug, windows
